[settings]
experimental = true
python.uv_venv_auto = true

[env]
TB_PROJECT_SOURCE = "f3_nation_test_utils"
TB_COVERAGE_EXTRA_ARGS = "--cov-fail-under=100"
COVERAGE_RCFILE = "configs/.coveragerc"

[tools]
uv = "0.7.20"
taplo = "0.10.0"
node = "24.4.1"
pnpm = "10.13.1"
mdbook = "0.4.52"
starship = "1.23.0"
